# Generated by Django 5.2.17 on 2026-09-13 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('property', '0003_remove_property_unique_property_name_per_user_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('occurred', 'Occurred'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('all_day', models.BooleanField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('user_participation_required', models.BooleanField(default=False)),
                ('user_presence_required', models.BooleanField(default=False)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='contact.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_contacts', to='event.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('all_day', True), ('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('all_day', False), ('end_time__isnull', False), ('start_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='event_has_valid_timing'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('user_presence_required', False), ('user_participation_required', True), _connector='OR'), name='event_presence_requires_participation'),
        ),
        migrations.AddConstraint(
            model_name='eventcontact',
            constraint=models.UniqueConstraint(fields=('event', 'contact'), name='unique_contact_attendance_per_event'),
        ),
    ]
