# Generated by Django 5.2.17 on 2026-09-17 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('property', '0003_remove_property_unique_property_name_per_user_ci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_has_valid_timing',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('all_day', True), ('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('all_day', False), ('start_time__isnull', False), models.Q(('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR')), _connector='OR'), name='event_has_valid_timing'),
        ),
    ]
