# Generated by Django 5.2.17 on 2026-08-26 09:30

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_property_name_per_user_ci',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('deleted_at__isnull', True)), name='unique_property_name_per_user_ci'),
        ),
    ]
